VIDEO_ID_COLUMN = "video_id"

NUMERIC_FIELD_MAP = {
    "点赞数": "likes",
    "评论数": "comments",
    "转发数": "shares",
    "收藏数": "collects",
    "粉丝数/w": "followers_w",
    "粉丝数/ml": "followers_million",
    "粉丝总数": "followers_total",
    "粉丝团人数": "fan_group_size",
    "带货口碑": "commerce_reputation",
    "视频带货力": "video_sales_power",
    "视频时长/s": "video_duration_s",
    "语速": "speech_rate",
    "带货商品数量": "goods_count",
    "近30日浏览w": "product_views_30d_w",
    "has_brand": "has_brand_flag",
    "hashtag": "hashtag_count",
    "text_score": "text_sentiment",
    "text_magnitude": "text_magnitude",
    "title_score": "title_sentiment",
    "title_magnitude": "title_magnitude",
    "facerate": "face_rate",
    "facenum_max": "face_count_max",
    "face_beauty": "face_beauty",
    "if_smile": "if_smile",
    "smile_num": "smile_count",
    "smile_rate": "smile_rate",
    "emotion_pos": "emotion_pos",
    "emotion_neg": "emotion_neg",
    "emotion_richness": "emotion_richness",
    "emotion_naturalness": "emotion_naturalness",
    "blurness": "blurness",
    "facequality": "face_quality",
    "face_area": "face_area",
    "value": "color_value",
    "saturation": "color_saturation",
    "hue": "color_hue",
    "Hue": "color_hue_aux",
    "colorfulness": "colorfulness",
    "视频文本总字符数": "video_text_chars",
    "视频标题总字符数": "title_chars",
    "视频文本_readability": "video_text_readability",
    "视频标题_readability": "title_readability",
    "视频文本Entropy": "video_text_entropy",
    "视频标题Entropy": "title_entropy",
    "concrete1": "concrete_1",
    "concrete2": "concrete_2",
    "IV": "info_value_1",
    "IV2": "info_value_2",
    "IV3": "info_value_3",
    "publish_hour": "publish_hour",
    "if_holiday": "if_holiday",
    "week0weekend1": "is_weekend",
}

PRODUCT_BUCKET_COLUMNS = {
    "food": "食品",
    "服饰": "服饰",
    "家居家电": "家居家电",
    "个护美妆": "个护美妆",
    "其他": "其他",
}

PRODUCT_BUCKET_CODE_MAP = {
    "1": "食品",
    "2": "服饰",
    "3": "家居家电",
    "4": "个护美妆",
    "5": "其他",
}

FAN_SEGMENTS_LOW_TO_HIGH = ("尾部", "腰部", "头腰", "头部")
